# Generated by Django 5.1.1 on 2024-10-29 10:22

import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('texts', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricalAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('html_content', models.TextField()),
                ('short_form', models.TextField(help_text='"|" indicates the start of a foot, ":" indicates a syllable boundary within a foot and "/" indicates a caesura.')),
                ('idx', models.IntegerField(help_text='0-based index')),
                ('urn', models.CharField(blank=True, max_length=255, null=True)),
                ('text_parts', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='metrical_annotations', to='texts.node')),
            ],
        ),
    ]
