# Generated by Django 5.1.1 on 2024-09-09 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=2)),
                ('sort_key', models.TextField()),
                ('unaccented', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('lang', 'text', 'pos')},
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=100)),
                ('parse', models.CharField(max_length=10)),
                ('sort_key', models.TextField()),
                ('parse_sort_key', models.CharField(max_length=12)),
                ('unaccented', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('lemma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='morphology.lemma')),
            ],
            options={
                'unique_together': {('lang', 'text', 'parse', 'lemma')},
            },
        ),
    ]
