# Generated by Django 5.1.1 on 2025-03-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('urn', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Commentaries',
            },
        ),
        migrations.CreateModel(
            name='CommentaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(help_text='0-based index')),
                ('urn', models.CharField(max_length=255, unique=True)),
                ('corresp', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='commentaries.commentary')),
            ],
            options={
                'verbose_name_plural': 'Commentary Entries',
                'unique_together': {('commentary', 'idx')},
            },
        ),
    ]
