# Generated by Django 5.2.3 on 2025-10-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaryentry',
            name='lemma',
            field=models.TextField(blank=True, null=True),
        ),
    ]
