# Generated by Django 5.1.5 on 2025-02-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('idx', models.IntegerField(blank=True, help_text='0-based index', null=True)),
                ('urn', models.CharField(help_text='urn:cite2:&lt;site>:senses.atlas_v1', max_length=255, unique=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='dictionaries.dictionaryentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('idx', models.IntegerField(blank=True, help_text='0-based index', null=True)),
                ('urn', models.CharField(help_text='urn:cite2:&lt;site>:citations.atlas_v1', max_length=255, unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='dictionaries.dictionaryentry')),
                ('sense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='dictionaries.sense')),
            ],
        ),
    ]
