# Generated by Django 5.1.5 on 2025-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_sense_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
