# Generated by Django 5.1.5 on 2025-03-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_dictionaryentry_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sense',
            name='depth',
            field=models.IntegerField(help_text='1 is first layer of senses'),
        ),
    ]
