# Generated by Django 5.2 on 2025-06-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_alter_sense_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='lang',
            field=models.CharField(default='grc', max_length=10),
            preserve_default=False,
        ),
    ]
