# Generated by Django 5.2.3 on 2025-10-20 16:57

from django.db import migrations, models
from django.utils.text import slugify


def slugify_labels(apps, schema_editor):
    Dictionary = apps.get_model("dictionaries", "Dictionary")

    for dictionary in Dictionary.objects.all():
        dictionary.slug = slugify(dictionary.label)
        dictionary.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_dictionary_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(slugify_labels)
    ]
