# Generated by Django 5.2.3 on 2025-10-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0006_dictionary_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='slug',
            field=models.SlugField(),
        ),
    ]
