# Generated by Django 5.1.1 on 2024-10-19 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0002_textalignment_metadata_textalignment_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAlignmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idx', models.IntegerField(help_text='0-based index')),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='alignments.textalignment')),
            ],
            options={
                'ordering': ['idx'],
            },
        ),
    ]
