# Generated by Django 5.1.1 on 2024-10-19 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0003_textalignmentrecord'),
        ('texts', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAlignmentRecordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='alignments.textalignmentrecord')),
                ('tokens', models.ManyToManyField(related_name='alignment_record_relations', to='texts.token')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_record_relations', to='texts.node')),
            ],
        ),
    ]
