# Generated by Django 5.1.1 on 2024-10-18 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='the tokenized value of a text part (usually whitespace separated)', max_length=255)),
                ('word_value', models.CharField(blank=True, help_text='the normalized version of the value (no punctuation)', max_length=255, null=True)),
                ('subref_value', models.CharField(blank=True, help_text='the value for the CTS subreference targeting a particular token', max_length=255, null=True)),
                ('position', models.IntegerField()),
                ('idx', models.IntegerField(help_text='0-based index')),
                ('ve_ref', models.CharField(blank=True, help_text='a human-readable reference to the token via a virtualized exemplar', max_length=255, null=True)),
                ('space_after', models.BooleanField(default=True)),
                ('text_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='texts.node')),
            ],
        ),
    ]
