# Generated by Django 5.1.1 on 2024-10-29 11:00

import django.db.models.deletion
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0001_initial'),
        ('texts', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('canvas', 'Canvas')], default='canvas', max_length=7)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('image_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('canvas_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('idx', models.IntegerField(help_text='0-based index')),
                ('urn', models.CharField(blank=True, max_length=255, null=True)),
                ('text_parts', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='image_annotations', to='texts.node')),
            ],
        ),
        migrations.CreateModel(
            name='ImageROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('image_identifier', models.CharField(max_length=255)),
                ('coordinates_value', models.CharField(max_length=255)),
                ('image_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi', to='image_annotations.imageannotation')),
                ('text_annotations', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='roi', to='annotations.textannotation')),
                ('text_parts', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='roi', to='texts.node')),
            ],
        ),
    ]
