# Generated by Django 5.1.1 on 2024-10-15 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnnotationCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('urn', models.CharField(help_text='urn:cite2:&lt;site>:text_annotation_collection.atlas_v1', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('idx', models.IntegerField(help_text='0-based index')),
                ('urn', models.CharField(blank=True, max_length=255, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotations.textannotationcollection')),
            ],
        ),
    ]
